### PR TITLE
Fix mixed content caused by steam images

### PR DESCRIPTION
**Pull request by xPaw**

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Dummy question since this is @connorshea's code and not mine (and I'm a non-web dev): Should http be in that URL...?

**Comment by xPaw** [comment]
Nope, omitting protocol makes the url protocol aware.

**Comment by flibitijibibo** [comment]
Good enough for me! Thanks for the patch.

**Comment by connorshea** [comment]
I believe at the time the Steam CDN didn't support HTTPS for its images, but I definitely should have done this from the start. We should probably remove the protocol from the store URL as well so users on HTTPS connections can be "opted-in" to use HTTPS if they click through.

**Comment by xPaw** [comment]
Store doesn't really support https on app urls, so there's no point in that at the moment.

**Comment by connorshea** [comment]
May as well future-proof, no harm in doing it for if/when Valve gets around to it.

**Pull request merged**
